### ISSUE TITLE
please use nav instead of ul this is not a valid practice 

### ISSUE THREAD

**Issue by Sara-Samer** [aqandeel53/frontend-project-1#3]
https://github.com/aqandeel53/frontend-project-1/blob/4c46eac436bbe1376ece66a35e24e48ee13586b8/index.html#L11-L46

**Comment by aqandeel53** [comment]
Dear Eng. Sara Samer , I updated my Rebo with your instructions .please use nav instead of ul this is not a valid practicewhere is DOCTYPE? https://github.com/aqandeel53/frontend-project-1 Thanks you ,  Sent from Mail for Windows From: Sara SamerSent: Wednesday, August 10, 2022 7:39 PMTo: aqandeel53/frontend-project-1Cc: SubscribedSubject: [aqandeel53/frontend-project-1] please use nav instead of ul this is not a valid practice (Issue #3) https://github.com/aqandeel53/frontend-project-1/blob/4c46eac436bbe1376ece66a35e24e48ee13586b8/index.html#L11-L46—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
